"""database changes for renderstyle

Revision ID: 77c38cea5235
Revises: efcbaee33642
Create Date: 2021-12-27 19:00:54.558994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c38cea5235'
down_revision = 'efcbaee33642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pointofinterest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('styleid', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pointofinterest_styleid_renderstyle'), 'renderstyle', ['styleid'], ['styleid'])
        batch_op.drop_column('style')

    with op.batch_alter_table('renderstyle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('styleversion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_removable', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_renderstyle_userid_user'), 'user', ['userid'], ['userid'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_styleid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_default_styleid_renderstyle'), 'renderstyle', ['default_styleid'], ['styleid'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_default_styleid_renderstyle'), type_='foreignkey')
        batch_op.drop_column('default_styleid')

    with op.batch_alter_table('renderstyle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_renderstyle_userid_user'), type_='foreignkey')
        batch_op.drop_column('is_removable')
        batch_op.drop_column('styleversion')
        batch_op.drop_column('userid')

    with op.batch_alter_table('pointofinterest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_pointofinterest_styleid_renderstyle'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'renderstyle', ['style'], ['styleid'])
        batch_op.drop_column('styleid')

    # ### end Alembic commands ###
