"""initial db migration config

Revision ID: 9b97ad4846ac
Revises: 
Create Date: 2021-12-10 04:44:33.876661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b97ad4846ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renderstyle',
    sa.Column('styleid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('style', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('styleid')
    )
    op.create_table('user',
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('displayname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('hashed_pw', sa.VARCHAR(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('displayname'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pointofinterest',
    sa.Column('poiid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('public', sa.BOOLEAN(), nullable=True),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('style', sa.INTEGER(), nullable=True),
    sa.Column('coord_x', sa.INTEGER(), nullable=True),
    sa.Column('coord_y', sa.INTEGER(), nullable=True),
    sa.Column('coord_z', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['style'], ['renderstyle.styleid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('poiid')
    )
    # ### end Alembic commands ###
